[tools]
luau-lsp = "JohnnyMorganz/luau-lsp@1.28.1"
rojo = "rojo-rbx/rojo@7.4.0-rc2"
selene = "Kampfkarren/selene@0.26.1"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.1"
