[package]
name = "dig1t/maid"
version = "1.0.4"
description = "Module part of the dig1t/roblox-modules repository"
license = "Apache-2.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["*.spec.luau"]

[dependencies]
Util = "dig1t/util@1.0.10"
