# https://github.com/nightcycle/occlusion-camera/blob/main/.github/workflows/release.yml

name: Release package

on:
  workflow_dispatch:
  push:
    paths:
      - 'version.txt'

jobs:
  publish:
    runs-on: ubuntu-latest

    outputs:
      TAG_NAME: ${{ steps.update-files.outputs.handle }}
      REPO_NAME: ${{ steps.update-files.outputs.handle }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          submodules: recursive

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get version
        id: version
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const core = require('@actions/core')
            const fs = require('fs');
            const version = fs.readFileSync('${{ github.workspace }}/version.txt', 'utf8')
            core.setOutput('version', version);

      - name: Update files with new version
        id: update-files
        shell: bash
        run: |
          REPO_OWNER=${{ github.repository_owner }}

          forward_repo_pattern="${REPO_OWNER}/"
          empty_str=""
          repo=${{github.repository}}
          REPO_NAME=${repo/${forward_repo_pattern}/${empty_str}}

          goal_version_str=${TAG_NAME#v}

          # read wally.toml file
          wally_toml_contents=$(<wally.toml)

          # swap out name
          target_name_line=$(echo "$wally_toml_contents" | grep -F "name = ")
          goal_name_line="name = \"${REPO_OWNER}/${REPO_NAME}\""
          wally_toml_contents="${wally_toml_contents/${target_name_line}/${goal_name_line}}"

          # swap out version
          target_version_line=$(echo "$wally_toml_contents" | grep -F "version = ")
          goal_version_line="version = \"${goal_version_str#v}\""
          wally_toml_contents="${wally_toml_contents/${target_version_line}/${goal_version_line}}"

          # update wally.toml file
          echo "$wally_toml_contents" > wally.toml

          # read package.json file
          default_json_contents=$(<package.json)
          target_json_version_line=$(echo "$default_json_contents" | grep -F "\"version\": ")
          goal_json_version_line="  \"version\": \"${goal_version_str#v}\","
          default_json_contents="${default_json_contents/${target_json_version_line}/${goal_json_version_line}}"

          # update package.json file
          echo "$default_json_contents" > package.json

          # read README.md file
          readme_contents=$(<README.md)
          target_readme_version_line=$(echo "$readme_contents" | grep -F "${REPO_NAME} = \"")
          goal_readme_version_line="${REPO_NAME} = \"${REPO_OWNER}/${REPO_NAME}@${goal_version_str#v}\""
          readme_contents="${readme_contents/${target_readme_version_line}/${goal_readme_version_line}}"

          # update README.md file
          echo "$readme_contents" > README.md

          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Commit files with new version and update tag
        run: |
          # Commit version update
          git config user.name "$(git log -n 1 --pretty=format:%an)"
          git config user.email "$(git log -n 1 --pretty=format:%ae)"
          git add --all
          git commit -m "Update to v${{ steps.version.outputs.version }}"
          git push -u origin main --force-with-lease --tags || true
          echo "Committed changes"

      # Create GitHub release
      - name: Create ${{ steps.version.outputs.version }} Runner Release
        uses: actions/create-release@master
        id: createRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.version.outputs.version }}"
          release_name: "v${{ steps.version.outputs.version }}"

      - name: Install aftman dependencies
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Install dependencies
        run: npm run build:dependencies

      - name: Publish to wally
        shell: bash
        env:
          WALLY_TOKEN: ${{ secrets.WALLY_TOKEN }}
        run: |
          rm -rf packages testez.toml .github node_modules .vscode
          mkdir -p ~/.wally
          printf "[tokens]\n\"https://api.wally.run/\" = \"%s\"" "$WALLY_TOKEN" >> ~/.wally/auth.toml
          wally publish

      - name: Build package place file
        run: rojo build -o ${{ steps.update-files.outputs.REPO_NAME }}.rbxl build.project.json

      - name: Upload Roblox level file to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.createRelease.outputs.upload_url }}
          asset_path: ${{ steps.update-files.outputs.REPO_NAME }}.rbxl
          asset_name: ${{ steps.update-files.outputs.REPO_NAME }}.rbxl
          asset_content_type: application/octet-stream
